<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="mbp16.local" failures="1" tests="1" name="Test" time="2.676" errors="0" timestamp="2020-04-21T22:24:36 GMT-04:00">
  <testcase classname="checkerpackage.CheckProductStock" name="checkIfProductIsOOS" time="0.107">
    <failure type="java.lang.AssertionError" message="did not expect to find [OUT OF STOCK] but found [OUT OF STOCK]">
      <![CDATA[java.lang.AssertionError: did not expect to find [OUT OF STOCK] but found [OUT OF STOCK]
at checkerpackage.CheckProductStock.checkIfProductIsOOS(CheckProductStock.java:33)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- checkIfProductIsOOS -->
</testsuite> <!-- Test -->
